spring:
  datasource:
      url: jdbc:mysql://localhost:3306/muziDemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: muzi
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: org.apache.commons.dbcp2.BasicDataSource
      resources:
        static-locations:
          classpath:/static/
  mybatis:
    mapper-locations: classpath:com.learning.springboot.mapper.*.xml
    config-location: classpath:mybatis/mybatis-config.xml
  logging:
    level:
      com.percussion.website: debug