package com.learning.springboot.model;

public class MemberInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.guid
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.name
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.password
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.mobile
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.email
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.photo
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.record_state
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    private String recordState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.guid
     *
     * @return the value of member_info.guid
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.guid
     *
     * @param guid the value for member_info.guid
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.name
     *
     * @return the value of member_info.name
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.name
     *
     * @param name the value for member_info.name
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.password
     *
     * @return the value of member_info.password
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.password
     *
     * @param password the value for member_info.password
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.mobile
     *
     * @return the value of member_info.mobile
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.mobile
     *
     * @param mobile the value for member_info.mobile
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.email
     *
     * @return the value of member_info.email
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.email
     *
     * @param email the value for member_info.email
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.photo
     *
     * @return the value of member_info.photo
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.photo
     *
     * @param photo the value for member_info.photo
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.record_state
     *
     * @return the value of member_info.record_state
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public String getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.record_state
     *
     * @param recordState the value for member_info.record_state
     *
     * @mbggenerated Thu Oct 18 16:46:13 CST 2018
     */
    public void setRecordState(String recordState) {
        this.recordState = recordState;
    }
}